### ISSUE TITLE
Typo? s/users/user/ in the Full Example?

### ISSUE THREAD

**Issue by richb-hanover** [therootcompany/async-router#2]
Thanks for the great video, and the work to make Express promise-safe.

In the **Full Example** in the README.md page, it says `return users;` and `res.json(users);` Should those refer to `user`? 

Also, in the **TL;DR**, it should probably say "... Swap out app for the async router..." (remove the extraneous "a")

Thanks again.

**Comment by coolaj86** [comment]
You're welcome.

Yes, those are probably typos. Feel free to PR and I'll pull it in soonish. (when I next work on this, probably within the week)

**Comment by coolaj86** [comment]
Fixed via #9
